name: sohan_flutter_cli
description: "A command-line tool to set up a Flutter project with predefined templates, folders, files, and dependencies."
version: 3.0.1
repository: https://github.com/Sohan-14/sohan_flutter_cli
homepage: https://github.com/Sohan-14/sohan_flutter_cli

environment:
  sdk: ^3.7.0

example:
  path: example

dependencies:
  args: ^2.4.2
  yaml: ^3.1.3
  yaml_edit: ^2.2.2

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0

executables:
  starter_temp_clean_getx: starter_temp_clean_getx
  starter_bd_calling_temp: starter_bd_calling_temp
